# Generated by Django 5.0.4 on 2025-03-10 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
